Добавляет наставника
htmlacademy-htmlcss/2086459-sedona-34 pull request #1
Opened 2022-05-28 20:37 UTC by KKKonstantin

2022-05-29 09:28 UTC, pavel-nyukalo requested changes

2022-05-29 09:28 UTC, pavel-nyukalo commented on Readme.md
> +* Наставник: `Павел Нюкало`.
Давай для единообразия добавим и мне ссылку. В markdown это `[Текст ссылки](сама ссылка)`

2022-05-29 11:31 UTC, KKKonstantin commented on Readme.md
> +* Наставник: `Павел Нюкало`.
Ок, скорректировал, прошу проверить

2022-05-30 04:59 UTC, pavel-nyukalo approved these changes

2022-05-30 04:59 UTC, merged