Добавляет разметку главной и модальной страниц сайта Седона
htmlacademy-htmlcss/2086459-sedona-34 pull request #2
Opened 2022-06-06 17:19 UTC by KKKonstantin

Добрый день, 
Прошу посмотреть разметку двух страниц сайта, в разметке страницы Каталог есть 2 комментария, прошу обратить внимание и помочь сделать хорошую разметку. Обе разметки были проверены через валидатор.

2022-06-07 06:21 UTC, pavel-nyukalo requested changes

2022-06-07 06:21 UTC, pavel-nyukalo commented on index.html
> +          </li>
Здесь несколько моментов.
1. Картинка все же относится к "настоящему городку", как и картинка моста дьявола, поэтому по логике они должны быть в одном `li`
2. Жилье, еда и сувениры уже не имеют нумерацию и как бы выпадают из логики. Можно сделать списком `ul` внутри первого `li` у нумерованного списка
3. Иконки дома, бургера и тд можно сделать декоративными и добавить через `css`. На контентные они не тянут

И получится примерно так:

красный - `ol`
синие - `li` у `ol`
зеленый `ul` внутри первого `li`

![image](https://user-images.githubusercontent.com/52506235/172307580-d0012457-b679-4817-9269-9b6f447b0e1f.png)

2022-06-07 06:21 UTC, pavel-nyukalo commented on index.html
> +        <img class="subscribe-description-image" src="#" alt="Фоновая фотография гор в городе Седоны">
Фоновую картинку сделаем как раз фоном, через `css`

2022-06-07 06:21 UTC, pavel-nyukalo commented on catalog.html
> +            <a class="navigation-link navigation-link-current" href="catalog.html">Гостиницы</a>
А здесь уже убрать ссылку на `catalog`, в нем и находимся

2022-06-07 06:21 UTC, pavel-nyukalo commented on catalog.html
> +       <img class="catalog-filter-image" src="#" alt="Фоновая фотография горы в городе Седоны">
Тоже сделаем через `css`

2022-06-07 06:21 UTC, pavel-nyukalo commented on catalog.html
> +        </ul>
С отступами немного поехало. Если работаешь в VSCode можешь вызвать командую строку через `Ctrl` + `P`, и набрать "отформатировать документ".

Не должно быть ситуации, когда вложенный тег находится на одном уровне с родительским, то есть:
```html
Не правильно
<ul>
<li>
</li>
</ul>

Правильно
<ul>
  <li>
  </li>
</ul>
```

2022-06-07 06:21 UTC, pavel-nyukalo commented on catalog.html
> +        <fieldset class="catalog-filter-group">
`fieldset` лучше в `form` делать, более семантично. [Пример](https://doka.guide/html/fieldset/#primer)

2022-06-07 06:21 UTC, pavel-nyukalo commented on catalog.html
> +        <!--Я так понял, этот блок мы не размечаем, он будет размечен в будущем, пока оставил место для него условно-->
Пока да, оставь

2022-06-07 06:21 UTC, pavel-nyukalo commented on catalog.html
> +        <button class="button-reset" type="submit">Сбросить</button>
Для "сбросить" есть отдельный `type` - `reset`

2022-06-07 06:21 UTC, pavel-nyukalo commented on catalog.html
> +        <!--Я не понимаю как тут сделать, помогите плс-->
Имеешь ввиду как цифру 38 подставлять? На данном курсе - никак, просто зашить ее в разметку. В любом случае это делается скриптами

2022-06-07 06:21 UTC, pavel-nyukalo commented on catalog.html
> +          <a class="service-card-button-rating button" href="#">Рейтинг: 8,5</a>
Думаю, рейтинг это не ссылка, просто информация

2022-06-07 06:21 UTC, pavel-nyukalo commented on catalog.html
> +        </ul>
Надо добавить еще три гостиницы

2022-06-08 18:28 UTC, KKKonstantin commented
index: 
1) поменял ссылки c index.html на #
2) сделал в section с классом advantages нумерованный список с помощью тэга ol
3) в section с классом advantages картинки поместил внутрь соответствующих li 
4) поместил Еда, Жилье и Сувениры в отдельный ненумеруемый ul
5) иконки внутри разделов Еда, Жилье и Сувениры убрал
6) удалена фоновая картинка в subscribe
7) 

catalog: 
1) поменял ссылки c catalog.html на #
2) удалена фоновая картинка в main-inner
3) поправил отступы
4) обернул fieldset в form
5) поменял type у кнопки Сбросить
6) поменял ссылку рейтинга на тэг p
7) добавил еще 3 гостиницы в список под классом service-list

дополнительно в catalog добавил:
1) добавил пагинацию 
2) добавил кол-во отображаемых элементов
3) добавил к section с классом options-housing h2 для семантики с классом visually-hidden - валидатору так больше нравится

2022-06-09 05:17 UTC, pavel-nyukalo approved these changes

2022-06-09 05:17 UTC, merged